export {default as About} from "./About/About"
export {default as Home} from "./Home/Home"
export {default as Contacts} from "./Contacts/Contacts"
export {default as Login} from "./Login/Login"
export {default as Packages} from "./Packages/Packages"
export {default as SignUp} from "./SignUp/SignUp"