export {default as About} from "./About/About"
export {default as Home} from "./Home/Home"
export {default as Contacts} from "./Contacts/Contacts"
export {default as Registration} from "./Registration/Registration"
export {default as Packages} from "./Packages/Packages"