export {default as About} from "./About/About"
export {default as Home} from "./Home/Home"
export {default as Contact} from "./Contact/Contact"
export {default as Login} from "./Login/Login"
export {default as Packages} from "./Packages/Packages"
export {default as SignUp} from "./SignUp/SignUp"
export {default as Services} from "./Services/Services"
export {default as MyProfile} from "./MyProfile/MyProfile"